### ISSUE TITLE
Chests rendered while using shaders are bugged

### ISSUE THREAD

**Issue by egirlcatnip** [FoundationGames/EnhancedBlockEntities#1]
Using Optifine with Opti-fabric mod breaks chest, shown on a picture below.
![image](https://user-images.githubusercontent.com/26607304/109468720-4bffa080-7a6d-11eb-9d41-5b3c4d01f9a3.png)

Same image, without usage of shaders
![image](https://user-images.githubusercontent.com/26607304/109468772-62a5f780-7a6d-11eb-9675-d7eb733c132d.png)

Note: _Chest's upper half renders correctly when opening chests_

**Comment by FoundationGames** [comment]
I wouldn't expect EBE to work well with OptiFine shaders. If you'd like a quick shaders solution i'd suggest checking out [Iris](https://github.com/IrisShaders/Iris/) or their [discord server](https://discord.gg/jQJnav2jPu). I notice that you're also using better grass and likely a few other optimizations, there are [alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) for these too. This may be quite a bit of work, but the nature of OptiFine isn't very mod friendly...

**Comment by egirlcatnip** [comment]
Thanks for the reply, just thought you might want to know :D
