### ISSUE TITLE
Chest textures have wrong orientation.

### ISSUE THREAD

**Issue by Xrey274** [FoundationGames/EnhancedBlockEntities#10]
No texture pack used, just vanilla textures. Some of the textures (like the lock and bottom of chest) are not oriented correctly.

With EBE:
![2021-03-07_14 40 13](https://user-images.githubusercontent.com/30723811/110240258-c3dd3780-7f53-11eb-8ce7-dd364177a0f1.png)

Without:
![2021-03-07_14 41 11](https://user-images.githubusercontent.com/30723811/110240273-d2c3ea00-7f53-11eb-84a2-6334ea21b71c.png)

**Comment by Xrey274** [comment]
Also lighting on the chest seems different.

**Comment by FoundationGames** [comment]
Will be fixed. Lighting cannot be changed, chests are being lit like normal blocks instead of in the odd way entities are lit.

**Comment by Xrey274** [comment]
Cool, I can't wait.

**Comment by FoundationGames** [comment]
Fixed in 0.2
