### ISSUE TITLE
Crash when Ring A Bell

### ISSUE THREAD

**Issue by ardissaps** [FoundationGames/EnhancedBlockEntities#101]
System, MC Version, Mods all [detailed here](https://paste.atlauncher.com/view/45c16af6-7076-4944-9fbb-abe020951ee5
). (please scroll to very bottom)

**Comment by Phoenix-Starlight** [comment]
Disable the bells I believe for the meantime. Also this issue is invalid as you are using NEC, see #56
You can help it be reopened by providing a crash without NEC.
(Also if you've edited the logs to make it look like you didn't use NEC you did a terrible job of it)

**Comment by ardissaps** [comment]
> 

Why would I want to edit the log, it is from AT Launcher upload log link. I don't even know what NEC is (before opening your link).

Edit : I still don't know what NEC is after opening the link provided. (my bad)
Edit2 : Ah found it! Not Enough Crash right, offcourse I am using it.
Edit3 : Yes in the meantime I disable chest and bell, but still using the the others.

I also use ETF as an addition, but disabled some option that they say would not be compatible.

**Comment by FoundationGames** [comment]
Not Enough Crashes is not recommended (or supported, unless the issue is a genuine oversight in the code) since it can (and usually **will**) put the game into an invalid state where random things can cause serious crashes.
