### ISSUE TITLE
Is the Performance significant if mostly I have only around 15 block entities in 12 render distance?

### ISSUE THREAD

**Issue by ardissaps** [FoundationGames/EnhancedBlockEntities#102]

**Comment by Phoenix-Starlight** [comment]
Your question is kinda hard to understand, but if I understand right: Yes it will still improve performance but the improvement might vary (because of a bunch of factors).

**Comment by ardissaps** [comment]
A thing I figured out is when we destroy block entity in vanilla it is not immediately disapear. But fixed when using EBE.

**Comment by burningtnt** [comment]
> A thing I figured out is when we destroy block entity in vanilla it is not immediately disapear. But fixed when using EBE.

If you play in another server with too high ping value, this would happend :(
Because your client would not destroy the block entity when you distroy the chest
Your client would only destroy the block entity if it receive the command from the server

**Comment by FoundationGames** [comment]
To answer the question in the title: No (unless you have extremely poor hardware)
EBE Helps mostly with dozens or hundreds of chests/beds/signs
