### ISSUE TITLE
Incompatibility with Better Christmas Chests

### ISSUE THREAD

**Issue by EssieFir** [FoundationGames/EnhancedBlockEntities#103]
Chests don't have their present texture when [Better Christmas Chests](https://modrinth.com/mod/better-christmas-chests) (BCC) is installed (with the option set to always in the BCC config & "Allowed" in Enhanced Block Entities Config)

**Comment by FoundationGames** [comment]
EBE will not work with mods that change chests visually like that, but someone might be able to make a resource pack that does a similar thing using EBE (since you can change the models for individual types of chests at liberty)
