### ISSUE TITLE
incompatibility with libjf

### ISSUE THREAD

**Issue by 0DamI0** [FoundationGames/EnhancedBlockEntities#104]
[latest.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/9034628/latest.log)

**Comment by Phoenix-Starlight** [comment]
The problem I see with this is that there isn't a mod named 'libjf' in there.
Can you please attach a log with libjf and not without libjf?

**Comment by 0DamI0** [comment]
well with libjf and EBE it simply crashes it's easily replicable

**Comment by Jamalam360** [comment]
LibJF is completely incompatible with Quilt, @FoundationGames I don't believe this is an EBE issue

**Comment by Jamalam360** [comment]
See Quilts incompatibly list: https://forum.quiltmc.org/t/mod-incompatibility-megathread/261/3

**Comment by 0DamI0** [comment]
it doesn't even work with fabric, when you remove it, it does

**Comment by Phoenix-Starlight** [comment]
Well then, can't you post the log or crash-report?
