### ISSUE TITLE
2 chests visible in same block

### ISSUE THREAD

**Issue by ewobee** [FoundationGames/EnhancedBlockEntities#110]
When i open the chest, the animation plays but also has it not playing at the same time, happens both with experimental chests on and off.

![2022-07-16_19 28 07](https://user-images.githubusercontent.com/80922756/179381411-f71eec55-e8f3-4102-bf62-d8b243938ee7.png)

![2022-07-16_19 28 25](https://user-images.githubusercontent.com/80922756/179381416-6411bb0f-a946-41cf-a409-f19c1b758e77.png)

**Comment by Ewobee** [comment]
Apparently, I just needed [indium](https://modrinth.com/mod/indium).

**Comment by ewobee** [comment]
Apparently, I just needed [indium](https://modrinth.com/mod/indium).
