### ISSUE TITLE
DashLoader Compatibility?

### ISSUE THREAD

**Issue by piebaker** [FoundationGames/EnhancedBlockEntities#112]
After having a read-through pull request & issues, just wondering as to the current (1.19.1) compatibility status of EBE with Dashloader? 
Some pull requests have compatibility pulled in, but some issues have it as problematic.

**Comment by burningtnt** [comment]
It seems that if EBE is used with Dashloader, chest (or shulker box) would display its close model even the chest is opening.
I guess DashLoader changed some basic codes.
Maybe we should code specially if Dashloader is loaded
(Chinese Player, not good at English :( )

**Comment by eltrevii** [comment]
@15801915131 i have the same issue without even using dashloader so it might not be dashloaders fault

**Comment by FoundationGames** [comment]
@15801915131 and @Aritz331 , make sure you have sodium and *indium* when using EBE (if those are both present, it could be another mod)

**Comment by eltrevii** [comment]
@FoundationGames yeah i found that i needed indium later after posting the comment, it works perfectly now

**Comment by piebaker** [comment]
Awesome, thanks all

**Comment by burningtnt** [comment]
Yes I have checked that I do use indium and sodium when using EBE.
But the problem (chest (or shulker box) would display its close model even it is opening.)

**Comment by burningtnt** [comment]
Gameversion: 1.18.1
Use the latest sodium, indium, dashloader, EBE and fabric
