### ISSUE TITLE
Crash when modifying certain models

### ISSUE THREAD

**Issue by StereoMadnessss** [FoundationGames/EnhancedBlockEntities#115]
I can't exactly wrap my head around why this occurs, but I will try to at least try to pinpoint what might be causing certain issues.
So it might be a crash with BlockStates or Models most likely, but I still don't know. Here is how to and what it does.

How to reproduce:
Get a pack I made ([BreakMe](https://www.curseforge.com/minecraft/texture-packs/breakme))
Then try loading it.

A video is attached:

https://user-images.githubusercontent.com/77188051/184519273-622b72c8-3eb9-4743-a66d-c7a3a41bea85.mp4

Here is also a crash log:
[crash.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/9332749/crash.txt)

**Comment by FoundationGames** [comment]
Please note _the name of the pack_

I do think that resource packs that put textures into invalid states should be handled much more elegantly than just crashing so that will likely be done
