### ISSUE TITLE
EnchantedBlockEntities crash on 1.16.2

### ISSUE THREAD

**Issue by SnooComics9452** [FoundationGames/EnhancedBlockEntities#116]
How to reproduce:
1. download fabric loader 0.11.3 1.16.2 and install it
2. download fabric-api-0.20.1+build.401-1.16 and EBE 0.4 for 1.16.x
3. launch it and it will crash when starting

0.1-0.3 also crashing

[crash-2022-08-16_17.21.15-client.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/9349423/crash-2022-08-16_17.21.15-client.txt)

**Comment by FoundationGames** [comment]
1.16 versions are no longer supported (have not been for a while)
