### ISSUE TITLE
Bells' smooth lighting is enabled

### ISSUE THREAD

**Issue by Madis0** [FoundationGames/EnhancedBlockEntities#123]
There seems to be an oversight with bells that have smooth lighting enabled by default, because chests, signs, beds and shulker boxes do not.

**Comment by FoundationGames** [comment]
Bells having smooth lighting enabled by default is intentional, since bells (the bell frame, at least) in vanilla are smoothly lit. Other block entities are not smoothly lit in vanilla, hence their default settings.
