### ISSUE TITLE
Block models conflicting with Sodium

### ISSUE THREAD

**Issue by Gavirium** [FoundationGames/EnhancedBlockEntities#126]
When I have your enhancedBlockEntities mod in version 0.7.1 in 1.19, together with Sodium version 0.4.4 many of the integrated models 
of your mod somehow interfere. You can for example still see the closed state of both chests/echest/shulker boxes.
I've also tested it with sodium 0.4.2, and that makes no different. 
![2022-11-08_03 34 47](https://user-images.githubusercontent.com/30010764/200462626-76724b86-ddc9-4983-a9a7-01377c26ff73.png)

**Comment by Timolino456** [comment]
You have to use the Indium mod when using EBE with Sodium.
