### ISSUE TITLE
[suggestion] add bed resource pack

### ISSUE THREAD

**Issue by Aces-and-Jacks** [FoundationGames/EnhancedBlockEntities#129]
So basically if this works the same or similar as better beds then maybe add a resource pack that looks good? Because currently any resource pack I use won't work with this mod, and I like the fancy bed resource pack used on better beds. 

Normally I'd just use the better beds mod but on 1.19.3 it breaks that mod and I don't think it'll be updated

**Comment by Julienraptor01** [comment]
> So basically if this works the same or similar as better beds then maybe add a resource pack that looks good? Because currently any resource pack I use won't work with this mod, and I like the fancy bed resource pack used on better beds. 
> 
> Normally I'd just use the better beds mod but on 1.19.3 it breaks that mod and I don't think it'll be updated

You don't need to add BetterBeds with EBE and can instead just use the RPs
Tho BetterBeds is updated to 1.19.3 which currently EBE isn't

**Comment by Aces-and-Jacks** [comment]
i've tried applying bed resource packs and none work

**Comment by Julienraptor01** [comment]
> i've tried applying bed resource packs and none work

It's weird because they should, i use the modified BetterBeds RP i created with EBE and they work perfectly
You have enhanced Beds enabled in EBE right ?
Make sure your mods are up to date too.

You can grab the RPs from here
https://github.com/TeamMidnightDust/BetterBeds/tree/main
Or there
https://github.com/TeamMidnightDust/BetterBeds/issues/2#issuecomment-1066191845
And as said on my comment on the issue above, i've tested the pack and they are working with EBE

**Comment by Aces-and-Jacks** [comment]
well I was using https://www.planetminecraft.com/texture-pack/better-beds-5752565/

better beds resource packs work fine but wanted to try something different

**Comment by Julienraptor01** [comment]
> well I was using https://www.planetminecraft.com/texture-pack/better-beds-5752565/
> 
> better beds resource packs work fine but wanted to try something different

This pack can't work on BetterBeds nor EBE since it instead use CEM to change the beds
You have to convert this pack manually to get it to work
Or maybe you could get it to work with CEM but that's very unsure anyway

**Comment by Aces-and-Jacks** [comment]
well I haven't tested it with better beds alone. I guess if it doesnt work on ebe it won't work on better beds

**Comment by YoshiRulz** [comment]
Just tried one of Better Beds' built-in packs and it worked fine.

**Comment by Aces-and-Jacks** [comment]
> > well I was using https://www.planetminecraft.com/texture-pack/better-beds-5752565/
> > better beds resource packs work fine but wanted to try something different
> 
> This pack can't work on BetterBeds nor EBE since it instead use CEM to change the beds You have to convert this pack manually to get it to work Or maybe you could get it to work with CEM but that's very unsure anyway

So based on this I'll go with resource packs do work as long as it's not CEM. Anyway ima close this since having a resource pack shipped with the mod isn't really needed and probably isn't going to be added anyway. I also kinda forgot about this issue. If I have any problems I'll just open up a new one.
