### ISSUE TITLE
Chest animation is broken when turning a chest into a double chest while the single chest was closing

### ISSUE THREAD

**Issue by CalXee** [FoundationGames/EnhancedBlockEntities#13]
Title explains all. While a chest is closing, if you turn that closing chest into a double chest, the chest you placed will just be placed closed instead of vanilla, where the chest you placed follows the animation of the closing chest. Sorry I only 
provided a screenshot, I cannot record videos due to technical difficulties. 
![2021-03-21_10 27 03](https://user-images.githubusercontent.com/68349758/111908705-9357cc00-8a30-11eb-85c4-f0156a672dc6.png)

**Comment by CalXee** [comment]
Also this might also happen when turning a single chest into a double chest while the single chest is opening, that is just harder to reproduce with one player.

**Comment by CalXee** [comment]
Can no longer reproduce this issue in version 0.3, closing the ticket. I will reopen this if need be.

**Comment by CalXee** [comment]
Reintroduced in 1.19, I only tested with Sodium+Indium though.

**Comment by FoundationGames** [comment]
Fixed in 0.7.1
