### ISSUE TITLE
[Minecraft 1.19.3] Invisible chests, signs, shulker boxes, beds and bell with QFAPI 5.0.0-beta.8+0.75.1 and QSL 4.0.0-beta.12

### ISSUE THREAD

**Issue by YukiAyase** [FoundationGames/EnhancedBlockEntities#136]
Chests (normal, trapped and ender chests), signs (both normal and hanging), beds, shulker boxes, and bells, seems to be invisible and has missing textures when interacted, it only happens with **QFAPI 5.0.0-beta.8+0.75.1 and QSL 4.0.0-beta.12** </br>
Properly works with Fabric API and any QFAPI versions lower than what is mentioned
It may be related to the latest change they've made with flattening resource packs in QSL 4.0.0-beta.12 </br> https://github.com/QuiltMC/quilt-standard-libraries/pull/270
</br>
**Latest Fabric API**
![2023-03-05_10 48 50](https://user-images.githubusercontent.com/64414315/222939370-379e2006-f174-4a64-a331-b914093be542.png)

![2023-03-05_10 49 30](https://user-images.githubusercontent.com/64414315/222939368-fcef1d38-48b6-4240-bd00-a11154c6ee86.png)
</br>
**QFAPI 5.0.0-beta.8+0.75.1 and QSL 4.0.0-beta.12**
![2023-03-05_10 59 10](https://user-images.githubusercontent.com/64414315/222939454-e512ac9c-2318-4ede-88e1-0cb49465f7e6.png)
![2023-03-05_10 53 02](https://user-images.githubusercontent.com/64414315/222939455-ce92bb38-68dd-4285-8a6f-5ca3b2addf7c.png)
![2023-03-05_10 53 04](https://user-images.githubusercontent.com/64414315/222939456-648b8559-cb92-40ff-a495-93bd523a560c.png)
![2023-03-05_10 53 19](https://user-images.githubusercontent.com/64414315/222939463-496ad045-49e0-4297-8a1d-8de729dcb0a9.png)

**Comment by FoundationGames** [comment]
Do you see any errors in your game log? If so, that might be EBE's code breaking against QSL's group resource pack flattening, and might explain why no resources seem to load

**Comment by YukiAyase** [comment]
> Do you see any errors in your game log? If so, that might be EBE's code breaking against QSL's group resource pack flattening, and might explain why no resources seem to load

From lines 490 to 553 I think are the relevant errors
https://mclo.gs/5BRZqUV

Edit: There're no other errors except for that

**Comment by FoundationGames** [comment]
The issue has been found, QSL's resource pack flattening replaces a critical piece of code that EBE uses (potential solutions may be explored)

**Comment by YukiAyase** [comment]
This issue is now fixed!
Quilt has released an update for QSL
[[1.19.3] QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13](https://modrinth.com/mod/qsl/version/5.0.0-beta.9+0.76.0-1.19.3)

**Comment by NattoRiisa** [comment]
i feel like a fix should be done for the mod itself too, as stated by LambdAurora

> Though, in the process of debugging I found out an issue in EBE itself, INVOKE_ASSIGN makes it so the injected pack is not present in the packs field of the class, using INVOKE instead should fix it. This is very important because QSL may recompute namespaces and it could lead to the pack being voided.

**Comment by FoundationGames** [comment]
> i feel like a fix should be done for the mod itself too, as stated by LambdAurora
> 
> > Though, in the process of debugging I found out an issue in EBE itself, INVOKE_ASSIGN makes it so the injected pack is not present in the packs field of the class, using INVOKE instead should fix it. This is very important because QSL may recompute namespaces and it could lead to the pack being voided.

Fixed in 0.8.1+
