### ISSUE TITLE
Please update to Minecraft version 1.20 for your module.

### ISSUE THREAD

**Issue by surfishs** [FoundationGames/EnhancedBlockEntities#150]
Please update to Minecraft version 1.20 for your module.

**Comment by JACKKY04** [comment]
Bump

**Comment by ghost** [comment]
> Please update to Minecraft version 1.20 for your module.

PR #151 has the updated mod

**Comment by allanonmage** [comment]
I'm checking on the mods I've included in my modpack to see where development is.  I told my players that it might be several months after 1.20 is released before all our mods are updated.  Will you be updating your mods?  Do you have an ETA when you will be adding support for the later versions?

I'm not familiar enough with Github to know what PR #151 does.  Does that mean they are working on it, but have not yet published it to Modrinth?
