### ISSUE TITLE
EBE v0.9 on MC 1.20.1 breaks with sodium, model dosen't work correctly while chest, trapped chest, enderchest and shulker box is open

### ISSUE THREAD

**Issue by sbn708** [FoundationGames/EnhancedBlockEntities#154]
Tested on minecraft 1.20.1 with Fabric API 0.84.0, Sodium 0.4.10 build 27 and EBE 0.9 with default resource pack

![2023-06-27_13 30 58](https://github.com/FoundationGames/EnhancedBlockEntities/assets/78650588/3e40c116-3438-46c4-9c32-f6b702a07bcb)
![2023-06-27_13 31 01](https://github.com/FoundationGames/EnhancedBlockEntities/assets/78650588/b87308b3-02e5-42f0-be17-d39d6ba53b8b)
![2023-06-27_13 31 03](https://github.com/FoundationGames/EnhancedBlockEntities/assets/78650588/4bcda401-7e88-42a8-8a35-de3a9e3bc533)
![2023-06-27_13 31 04](https://github.com/FoundationGames/EnhancedBlockEntities/assets/78650588/9b066e7d-ebe5-4b4e-947d-21558cb4323a)
![2023-06-27_13 31 07](https://github.com/FoundationGames/EnhancedBlockEntities/assets/78650588/c9649c7c-e7c1-466b-8656-8dcfa4e3d344)

**Comment by FoundationGames** [comment]
Did you install Indium?

**Comment by sbn708** [comment]
You right I forgot install Indium and sorry about that
