### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by Avakining** [FoundationGames/EnhancedBlockEntities#187]

**Comment by Jackuhlf** [comment]
bump

**Comment by Brokkonaut** [comment]
You can build it if you take my pr for 1.20.2 - but you will first have to build [arrp](https://github.com/Devan-Kerman/ARRP) (because their repo is currently down) and add that to your local repo or something like that.

**Comment by Squtzy** [comment]
Hoping to see a update for 1.20.2 soon :/

**Comment by TiboOpGithub** [comment]
Is there being worked on a 1.20.2 version at the moment?

**Comment by Poopooracoocoo** [comment]
@TiboOpGithub #189

**Comment by Squtzy** [comment]
> @TiboOpGithub #189

Is FoundationGames not working on this anymore/currently or why has this not been update if there are pull requests too?

**Comment by Madis0** [comment]
> Is FoundationGames not working on this anymore/currently or why has this not been update if there are pull requests too?

Pull requests still require reviews and testing, so that's the best thing you can help with.

**Comment by Squtzy** [comment]
> > Is FoundationGames not working on this anymore/currently or why has this not been update if there are pull requests too?
> 
> Pull requests still require reviews and testing, so that's the best thing you can help with.

Yeah my bad, that's what I was meaning. But it seems to me like the mod author is inactive hence my question. Would help out with PR if I knew coding and stuff :/

**Comment by Brokkonaut** [comment]
The PR is ready for several weeks now and has been thoroughly tested. I don't know why there is no reaction of @FoundationGames yet, but I suspect he simply didn't have the time to look at it.

**Comment by Squtzy** [comment]
> The PR is ready for several weeks now and has been thoroughly tested. I don't know why there is no reaction of @FoundationGames yet, but I suspect he simply didn't have the time to look at it.

Ah I see, thanks for the reply 👍 Like I mentioned above I would help out with PR's if I knew coding

**Comment by Zorklis** [comment]
https://github.com/FoundationGames/EnhancedBlockEntities/pull/189#issuecomment-1756608625
Works great

**Comment by Brottweiler** [comment]
Solved in 67a2aa643dcef60f37a22d3a4190cb40eebe3e7f?

**Comment by Avakining** [comment]
Yep!
