### ISSUE TITLE
I NEED THIS MOD FOR 1.20.4!!!

### ISSUE THREAD

**Issue by Epik0rangutan** [FoundationGames/EnhancedBlockEntities#205]
I NEED THIS MOD FOR 1.20.4 PLEASE UPDATE IT OR I AM GONNA EAT MY FINGERS OFF JAJAJAJAAJ

**Comment by stitch97** [comment]
It works on 1.20.4

**Comment by devjta** [comment]
From another post, this one should work: https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities/files/4901159

**Comment by Epik0rangutan** [comment]
> From another post, this one should work: https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities/files/4901159

Thank you
