### ISSUE TITLE
Incompatible with simple drawers

### ISSUE THREAD

**Issue by IAmSneak** [FoundationGames/EnhancedBlockEntities#21]
Game doesn't load with simple drawers and latest branch of this mod.

https://www.curseforge.com/minecraft/mc-mods/simple-drawers

**Comment by FoundationGames** [comment]
I cannot help you unless you post a crash log, commit hash of the commit on the branch you say you are using or some more information. You also should be using the latest release of the mod on CurseForge or Modrinth, and not the indev branch.

Issue will be closed if no further context is provided

**Comment by IAmSneak** [comment]
enhanced block entities 0.1 (from modrinth)
fabric api (0.32.5)
simple drawers (1.8.0)
minecraft 1.16.4

After launching the game it does this

https://user-images.githubusercontent.com/66091019/115126193-4e757580-9f9b-11eb-8dfa-ff9576b2e2f5.mp4

**Comment by IMS212** [comment]
that is not a log file, can you get one from .minecraft\logs\latest.log ?

**Comment by IAmSneak** [comment]
this should be it
[2021-04-17-4.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/6330089/2021-04-17-4.log)

**Comment by FoundationGames** [comment]
Please post this on a paste site

**Comment by spiralhalo** [comment]
The issue seems to be on SimpleDrawers side and I've made a PR to fix it.
