### ISSUE TITLE
1.20.5 and 1.20.6 support

### ISSUE THREAD

**Issue by lzm11111111** [FoundationGames/EnhancedBlockEntities#210]
No more I want to saying.

**Comment by Brokkonaut** [comment]
There are some dependencies that are not yet updated, so I think we have to wait.

**Comment by mucookul** [comment]
After a bit of research in `build.gradle` it seems the only thing stopping you is SpruceUI, luckily there is a updated architectuary port called ObsidianUI

**Comment by UltimatChamp** [comment]
There is an open 1.20.6 pr for SpruceUI.

**Comment by BobzBlue** [comment]
It may have something to do with changes to the pot.

**Comment by Brottweiler** [comment]
It is updated now. :)
