### ISSUE TITLE
Decorated pot appears invisible when Sodium is installed

### ISSUE THREAD

**Issue by muzikbike** [FoundationGames/EnhancedBlockEntities#213]
Other block entities that are enhanced seem to work fine - this appears to be a decorated pot issue only. Issue is not present with only EBE installed, or only Sodium installed.
![2024-06-05_23 26 33](https://github.com/FoundationGames/EnhancedBlockEntities/assets/52297970/fd63edd7-1c3c-4180-86b6-c0e4595734d6)
![2024-06-05_23 26 46](https://github.com/FoundationGames/EnhancedBlockEntities/assets/52297970/ac007fbd-b678-4954-b6bf-d52d1a5bc888)

**Comment by FoundationGames** [comment]
Cannot reproduce this issue in 1.20.4 or 1.20.6. As stated on the mod's README and Modrinth/CurseForge pages, make sure you have [Indium](https://modrinth.com/mod/indium) installed when using with Sodium.

**Comment by muzikbike** [comment]
Wasn't Indium as a requirement deprecated in recent versions or am I misreading things?

**Comment by FoundationGames** [comment]
The FAQ section of the mod pages are outdated, the developers behind Sodium no longer seem to have plans or a priority for built-in Fabric Rendering API support. You will need Indium when using Sodium with most mods that use advanced block models for the foreseeable future.

**Comment by muzikbike** [comment]
Gotcha. Can confirm this is no longer an issue with Indium installed.
