### ISSUE TITLE
Decorated pot reverts to entity model when interacted with

### ISSUE THREAD

**Issue by muzikbike** [FoundationGames/EnhancedBlockEntities#214]
Found while testing #213.

We can tell that it's the entity model due to interior faces becoming visible again, which aren't part of the decorated pot's block model from the mod. Rendering said model as an entity is fine in this case, but it should use the actual block models rather than the deprecated entity model.

![2024-06-06_07 32 08](https://github.com/FoundationGames/EnhancedBlockEntities/assets/52297970/e2666bca-eebe-47a4-9751-f5f29a4da400)
![2024-06-06_07 32 20](https://github.com/FoundationGames/EnhancedBlockEntities/assets/52297970/680e37f5-a03a-4070-a309-41c0d0670a54)

**Comment by FoundationGames** [comment]
That specific interior face _**is**_ part of the decorated pot baked block model added by EBE. The animated decorated pot is being rendered using the block models, as implemented [here](https://github.com/FoundationGames/EnhancedBlockEntities/blob/1.20.6/src/main/java/foundationgames/enhancedblockentities/client/render/entity/DecoratedPotBlockEntityRendererOverride.java) and declared [here](https://github.com/FoundationGames/EnhancedBlockEntities/blob/1.20.6/src/main/java/foundationgames/enhancedblockentities/EBESetup.java#L442)

**Comment by muzikbike** [comment]
3am brain, disregard this
