### ISSUE TITLE
Chest of "Minecart with Chest" not shown in game (with Indium and sodium next branch)

### ISSUE THREAD

**Issue by DreamHelium** [FoundationGames/EnhancedBlockEntities#22]
Although Minecart with Chest is used not very often in game and it's not a big problem, it's still a issue.
Detail could be seen in the gif below.
![Peek 2021-04-28 17-35](https://user-images.githubusercontent.com/48383878/116385186-1ef02400-a84b-11eb-9367-4d93d3b5a289.gif)

**Comment by FoundationGames** [comment]
Known issue, please check before creating an issue.
Closed - duplicate
