### ISSUE TITLE
Chests appear visually to be both opened and closed when you open a chest

### ISSUE THREAD

**Issue by AstudilloMarillo** [FoundationGames/EnhancedBlockEntities#223]
Minecraft 1.21, EBE 0.10.1 on Fabric.
This only happens when Enhanced Chests option is set to 'on' of course. Also effects Ender Chests.
Here's a screenshot of the effect:

![image](https://github.com/FoundationGames/EnhancedBlockEntities/assets/136191659/f541214c-44f6-486a-8461-e0e836b56e4a)

**Comment by AstudilloMarillo** [comment]
Setting Enhanced Shulker Boxes to 'on' also makes this effect Shulker Boxes:

![image](https://github.com/FoundationGames/EnhancedBlockEntities/assets/136191659/05a0a584-3142-414f-b278-764b3cd7b70a)

**Comment by Barkells** [comment]
Its because you do not have indium installed, its now out for 1.21 so just install that and you will be good to go!

**Comment by AstudilloMarillo** [comment]
> Its because you do not have indium installed, its now out for 1.21 so just install that and you will be good to go!

Ohhh, thank you! I didn't know that was depended on Indium. Was already waiting for that to come out, installed it right away and it works :)
