### ISSUE TITLE
optifabric incompatible

### ISSUE THREAD

**Issue by StijnReijnders** [FoundationGames/EnhancedBlockEntities#23]
I think the new version is incompatible with the latest version of optifabric, it crashes on startup with the latest pre an normal release of optifine. The 0.1 version is fine, but the 0.2 version crashes.

**Comment by FoundationGames** [comment]
Please provide a game log file, and put it on a paste site such as Hatebin or Paste.gg.

**Comment by StijnReijnders** [comment]
https://paste.ee/p/d5YqF
hope this works

**Comment by FoundationGames** [comment]
This crash doesn't have to do with EBE, it's because of BetterBiomeBlend
