### ISSUE TITLE
Incompatible with Optifabric

### ISSUE THREAD

**Issue by AlphaKR93** [FoundationGames/EnhancedBlockEntities#24]
EBE 0.2 conflicts with Optifabric when opening settings screen. I think it's because of the Configuration Screen added to the 0.2 version. Here is the error log: https://pastebin.com/raw/JyVDfxDN

**Comment by AlphaKR93** [comment]
I think it would be better to add it to Modmenu Screen than to add Configuration Screen to Settings Screen.

**Comment by IMS212** [comment]
does this happen without fabric zero? (it's known to cause issues sometimes)

**Comment by FoundationGames** [comment]
No this is a known issue and is already fixed in development, next release will fix this and also let you access the screen from Mod Menu

**Comment by FoundationGames** [comment]
Fixed in 0.3.1
