### ISSUE TITLE
Compatibility with Better Christmas Chests

### ISSUE THREAD

**Issue by CalXee** [FoundationGames/EnhancedBlockEntities#25]
It would be great if this mod is eventually compatible with Better Christmas Chests. According to Foundation, these mods doesn't work at all together.

https://www.curseforge.com/minecraft/mc-mods/better-christmas-chests

**Comment by FoundationGames** [comment]
This will likely never happen as Better Christmas Chests uses a custom-namespaced file structure as well as has code that simply wouldn't work with the structure of EBE. The only reasonable way to "add compatibility" would be to check if the mod is loaded and run completely custom and separate code. 
An alternative to this is to allow you to apply a Christmas Chest model to any chest optionally in resource packs. This option will be considered.

**Comment by CalXee** [comment]
I see, thanks for the explanation. :)
