### ISSUE TITLE
Chest's model bug when using Shaders

### ISSUE THREAD

**Issue by NaiNonTH** [FoundationGames/EnhancedBlockEntities#27]
Image --> https://imgur.com/a/1TdwYdT

According to the images above, You'll see that the chest's model loaded incorrectly with shaders (Also, some shaders make chests invisible). But it's fine without shaders

**Comment by triphora** [comment]
How are you applying these shaders? (i.e., Iris, Canvas, OptiFine...?)

**Comment by NaiNonTH** [comment]
> How are you applying these shaders? (i.e., Iris, Canvas, OptiFine...?)

Optifine :)

**Comment by NaiNonTH** [comment]
More than that, Bell models kinda bug too

**Comment by jaz000** [comment]
I don't have either canvas or optifine (or sodium ...) but I also have invisible vanilla chests ...

thinking of possible clashes I have lithium and phosphor and lambdynamiclights ... (+ a lot more!)

full modlist:
https://pastebin.com/cNPFEahD

**Comment by DieuDeGlace** [comment]
@NaiNonTH how did you even get it to "work" with enhanced block entities? when i use optifine and optifabric it doesnt do anything

**Comment by FoundationGames** [comment]
Extremely old issue, but for anyone wondering now, OptiFine support for EBE has long since ended
