### ISSUE TITLE
Incompatible with Secret Rooms

### ISSUE THREAD

**Issue by boafur** [FoundationGames/EnhancedBlockEntities#29]
Having the Secret Rooms mod installed with EBE causes chests to become invisible.
Log file: https://pastebin.com/aRHWv734
Modlist: Sodium, Indium, EBE, Fabric API 0.34.2, Secret Rooms

Secret Rooms CurseForge: https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric/

**Comment by FoundationGames** [comment]
should be fixed in 0.5
