### ISSUE TITLE
Resource pack injection won't work if vanilla is moved

### ISSUE THREAD

**Issue by SpacEagle17** [FoundationGames/EnhancedBlockEntities#31]
The only mods I'm using for this test is ebe 0.3.1, fabric API 0.34.2, and replaymod 2.5.2. It's 1.16.5 and the fabric loader version is 0.11.3 I'm using jdk 16 in case that is relevant.
The chests, bells and signs appear invisible when using replaymod.
When I remove replaymod and use all my other mods it works just fine (then it also works fine with shaders)
Video: https://www.youtube.com/watch?v=rkqO8zRmX0A
![2021-05-27_11 27 06](https://user-images.githubusercontent.com/46494907/119802940-49331100-bedf-11eb-8e84-a00e83a68ccb.png)

![2021-05-27_11 27 15](https://user-images.githubusercontent.com/46494907/119802943-49331100-bedf-11eb-95eb-5b3c74ccdd35.png)

![2021-05-27_10 29 30](https://user-images.githubusercontent.com/46494907/119802929-47694d80-bedf-11eb-90cb-5454802feb96.png)
My mod list (without replaymod):
![image](https://user-images.githubusercontent.com/46494907/119803805-14738980-bee0-11eb-83d1-653b2c967291.png)
I hope this helps

**Comment by MenacingPerson** [comment]
I'm having this issue too.

**Comment by Sanluli36li** [comment]
I tried only replaymod and ebe, same

**Comment by Johni0702** [comment]
> > You need to go into Resource Packs and then reorder Vanilla to be above Fabric Mods, after which the glitch happens
>
> This happens for me even without ReplayMod installed. So please do report this on Enhanced Block Entities' issue tracker.
As far as I can tell, that is all there is to this. EBE simply breaks when the bottom-most pack is anything other than the vanilla "Default" pack. It doesn't actually matter what's there instead - Fabric Mods, Programmer Art or ReplayMod's internal pack - it'll break in any case.

https://github.com/ReplayMod/ReplayMod/issues/532#issuecomment-903094224

**Comment by FoundationGames** [comment]
EBE has to override vanilla resources to work since it replaces vanilla resource files. Changing the resource pack selection so that the default resources override modded resources will break EBE and likely several other mods.
Issue was also noted as fixed in the latest ReplayMod release.

**Comment by Johni0702** [comment]
> EBE has to override vanilla resources to work since it replaces vanilla resource files. Changing the resource pack selection so that the default resources override modded resources will break EBE

But that's not what I said. EBE will break even when the relation between modded and vanilla pack is unchanged. It is enough for **anything** other than Vanilla to be the bottom most pack and EBE will break, even if that is an empty pack.

> Issue was also noted as fixed in the latest ReplayMod release.

It was "fixed" in so far that ReplayMod no longer creates an invisible resource pack and therefore can no longer **trigger** this bug. The bug itself is in EBE and has nothing to do with RM (except that RM used to be one way to trigger it).

**Comment by FoundationGames** [comment]
EBE should not break as long as vanilla is below fabric mods and any additional pack above doesnt overwrite the chest blockstate files. Could you show an example of an arrangement that breaks EBE?

**Comment by Johni0702** [comment]
![](https://i.johni0702.de/p1Gv6.png)

I'm not guessing here. It's plainly obvious from looking at your code, EBE just inserts its pack at index 1, so if anything other than the Vanilla pack is at index 0, then your pack cannot possibly overwrite the vanilla blockstate files: https://github.com/FoundationGames/EnhancedBlockEntities/blob/bddd1be2b07f43043bf409cbbd6b2f74c8d758a3/src/main/java/foundationgames/enhancedblockentities/mixin/ReloadableResourceManagerImplMixin.java#L28-L35

**Comment by FoundationGames** [comment]
That actually makes sense
I believe I write that under the assumption that the vanilla resources stay at 0 and can't be moved

**Comment by Madis0** [comment]
Just to confirm, is this issue fixed with 0.5? @FoundationGames

**Comment by FoundationGames** [comment]
fixed in 0.5 yes
