### ISSUE TITLE
[SUGGESTION] Prismarine animation

### ISSUE THREAD

**Issue by srnyx** [FoundationGames/EnhancedBlockEntities#32]
Prismarine has a very slight animation where it turns from blue to green and then back again within a span of about a minute.
I'm not sure if this would increase performance at all, but here is more info about it: https://minecraft.fandom.com/wiki/Prismarine#Usage

Maybe the mod could disable this.

**Comment by DragonEggBedrockBreaking** [comment]
This mod is supposed to not remove animations from stuff for performance, e.g. chests. If you use sodium, you can use a mod called [Sodium Extra](https://www.modrinth.com/mod/sodium-extra) to disable certain animations, including block animations from stuff like prismarine, sea lanterns, magma blocks and crimson/warped stems.

**Comment by srnyx** [comment]
> This mod is supposed to not remove animations from stuff for performance, e.g. chests. If you use sodium, you can use a mod called [Sodium Extra](https://www.modrinth.com/mod/sodium-extra) to disable certain animations, including block animations from stuff like prismarine, sea lanterns, magma blocks and crimson/warped stems.

Ohhhhh, ok. Forgot about Sodium Extra haha
Thanks for the quick response.
