### ISSUE TITLE
Bell swinging texture does funky stuff on 1.17

### ISSUE THREAD

**Issue by NoComment1105** [FoundationGames/EnhancedBlockEntities#38]
When you click the bell the main bell texture stays there but then the swinging one fades through it
This is fixed by turning off enhanced bells (obviously imo)

https://user-images.githubusercontent.com/67918617/124973470-7832bb80-e023-11eb-969c-66c8dcc67029.mp4

**Comment by NoComment1105** [comment]
Sodium go brrrr

**Comment by Janfel** [comment]
Can this please be reopened? This is an incompatibility with Sodium that should be investigated. I can also reproduce this with version 0.3.1 on Minecraft 1.16.5. I have also noticed, that using [Indium](https://github.com/comp500/Indium) as compiled from https://github.com/comp500/Indium/commit/a997c5583c1d995eb0da393d1784805bae92454a fixes this issue.

**Comment by edwloef** [comment]
That's just sodium not having full FRAPI support yet, and will eventually be fixed on their end.

**Comment by Janfel** [comment]
That explains it, thank you.

**Comment by FoundationGames** [comment]
> Can this please be reopened? This is an incompatibility with Sodium that should be investigated. I can also reproduce this with version 0.3.1 on Minecraft 1.16.5. I have also noticed, that using [Indium](https://github.com/comp500/Indium) as compiled from https://github.com/comp500/Indium/commit/a997c5583c1d995eb0da393d1784805bae92454a fixes this issue.

The result of my Investigation:
you need Indium because sodium doesn't support FRAPI
Hopefully this will help.
