### ISSUE TITLE
Incompatible with DashLoader

### ISSUE THREAD

**Issue by Huskydog9988** [FoundationGames/EnhancedBlockEntities#39]
Currently Enhanced Block Entities lacks support for DashLoader, Minecraft simply refuses to boot. If I had to guess, Id say that Dash doesn't like how you implemented baked block models.

**Comment by FoundationGames** [comment]
#30
DashLoader will not automatically work with mods that add custom baked model behavior, explicit compatibility needs to be added

**Comment by RDKRACZ** [comment]
>#50

#30

**Comment by Poopooracoocoo** [comment]
What's the status of this issue and the relevant PR?

**Comment by DioEgizio** [comment]
#73
