### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by K0-RR** [FoundationGames/EnhancedBlockEntities#4]
Is there any sense to use this mod for a small server where there are only a few chests visible?
Can’t this be a part of Sodium and Indium? Why not make a PR or sth? I’m not a dev so this may be a stupid question, sorry.

**Comment by K0-RR** [comment]
Also does this mod do anything with signs to prevent [this bug](https://bugs.mojang.com/browse/MC-5169)?
For example - https://www.curseforge.com/minecraft/mc-mods/mc-5169-fix

**Comment by FoundationGames** [comment]
The features added by this mod make major changes to chest rendering, the kind of changes that wouldn't make sense in Sodium. Indium is not an optimization mod, it's a compatibility mod for Sodium. Giving players the option to use this or not was the best choice for me to go along with. Currently EBE doesn't affect sign rendering in any way, although it's being worked on for the next update!
Closed issue, no problem to resolve, question has been answered
