### ISSUE TITLE
Top part of chest flickers for a short amount of time when closing

### ISSUE THREAD

**Issue by he3als** [FoundationGames/EnhancedBlockEntities#41]
# Description
With Sodium and Indium (while closing a chest) the top part of the chest will flicker for a very short amount of time. 

# Information
Does not happen without Sodium and Indium, I am using the latest version for 1.17.1 from Modrinth. I have a 240hz monitor, not sure if this flicker will show up on 60hz (I am not sure).

# Log
https://paste.ee/p/HbPGA

# Screenshots/recording
![image](https://user-images.githubusercontent.com/65787561/126971993-ada3e1e1-e11a-4688-944b-e01487c0ed24.png)
![WCMr46PomU](https://user-images.githubusercontent.com/65787561/126972369-c393376c-0594-47f1-8bb3-cf197efeac73.gif)

**Comment by FoundationGames** [comment]
Should be completely fixed in 0.5 except if using sodium, though this is due to something sodium does that is beyond my control

**Comment by Poopooracoocoo** [comment]
I just made recordings and was about to file an issue. Mind adding that to the readme? @FoundationGames
And is there an issue in the Sodium repo?

**Comment by muzikbike** [comment]
I still seem to be experiencing this with fabric-api-0.56.1+1.19, enhancedblockentities-0.7.1+1.19, sodium-fabric-mc1.19-0.4.2+build.16 and indium-1.0.6+mc1.19:
![2022-06-24_08 17 03_2](https://user-images.githubusercontent.com/52297970/175490361-526fc90d-56a9-4630-9df7-d46f1ed096c1.png)
