### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by Brottweiler** [FoundationGames/EnhancedBlockEntities#42]
I am not sure if this is out of scope or not, but since this mod has resource pack support, I'd like to make my chests full block size and _not_ have the lid open when you access the chest.

I tried to disable the lid somehow using the json model files, but I wasn't successful. Is there a way to do this, or could it be an option in the settings to disable the lid opening? Thanks!

**Comment by FoundationGames** [comment]
Make the lid model have no model elements, it will be an empty model
Then make the other two models be full blocks

**Comment by Brottweiler** [comment]
> Make the lid model have no model elements, it will be an empty model

Thanks for the answer! For some reason, last time I tried this I recall it didn't work. But I just did it now again to confirm and you are right, I've solved it. Thank you!
