### ISSUE TITLE
Chests, beds etc are invisible

### ISSUE THREAD

**Issue by emielderckx** [FoundationGames/EnhancedBlockEntities#44]
While using these mods chests are invisible even when using indium.

![image](https://user-images.githubusercontent.com/35953244/127779596-a4dc3eac-5deb-4a71-a32c-55ce8706f66e.png)

When turning off enhanced chest everything is fine. Same for beds etc

Clients can even crash when clicking on a chest, bed or bell

**Comment by Modsynite** [comment]
The only similar mods I have with yours:

- Hydrogen
- Krypton
- LazyDFU
- Litematica
- Malilib
- Lithium
- Sodium (custom version for ReplayMod)
- Startlight
- Iris

**Comment by Navota** [comment]
If you are using a resource pack, open it and delete chest.json in *assets\minecraft\blockstates\

**Comment by srnyx** [comment]
> The only similar mods I have with yours:
> 
> * Hydrogen
> * Krypton
> * LazyDFU
> * Litematica
> * Malilib
> * Lithium
> * Sodium (custom version for ReplayMod)
> * Startlight
> * Iris

I have all the same mods except for Litematica

> If you are using a resource pack, open it and delete chest.json in *assets\minecraft\blockstates\

Disabled all my resourcepacks and still happens

**Comment by FoundationGames** [comment]
Known issue, ReplayMod adds an invisible resource pack and that messes with EBE's flawed resource pack injection. Move vanilla to the bottom of your resource packs (even if it already is)

**Comment by srnyx** [comment]
> Move vanilla to the bottom of your resource packs (even if it already is)

What do you mean "even if it already is"

**Comment by FoundationGames** [comment]
Move the default resources down a bunch of times in the resource pack menu even if it is at the bottom

**Comment by srnyx** [comment]
> Move the default resources down a bunch of times in the resource pack menu even if it is at the bottom

Ohhhhh I see now. That's really annoying lol
*Gonna keep that in mind so I can have invisible signs lol*
