### ISSUE TITLE
Chests are weird

### ISSUE THREAD

**Issue by NotADinosaur** [FoundationGames/EnhancedBlockEntities#45]
![2021-08-09_16 49 57](https://user-images.githubusercontent.com/76700400/128789588-61f9aec6-7d46-404f-9f8a-86ec125603a9.png)

**Comment by FoundationGames** [comment]
Duplicate, check if your issue exists before reporting

**Comment by NotADinosaur** [comment]
Sorry. I did take a quick look but I guess I missed it. Which issue is the one this is a duplicate of? I really can’t find one.
