### ISSUE TITLE
Nether Portal Rendering Issue

### ISSUE THREAD

**Issue by Precizne** [FoundationGames/EnhancedBlockEntities#46]
Nether Portal texture is broken when using fancy nether portal option in Complementary Shaders. I tested but it only happens when both Lambdabettergrass and EBE are enabled along with Complementary Shaders v4.2 dev3 with fancy portal on Iris.

Mods:
fabric-api-0.37.2+1.17.jar
fabric-language-kotlin-1.6.3+kotlin.1.5.21.jar
iris-mc1.17-1.1.1
indium-1.0.0+mc1.17.1.jar
starlight-1.0.0-RC3+fabric.1.17.x.jar
lithium-fabric-mc1.17.1-0.7.3.jar
lambdabettergrass-1.2.0+1.17.jar
enhancedblockentities-0.4.1+1.17.jar

Complementary Shaders v4.2 dev3 on Iris ; Fancy Nether Portal Enabled through common.glsl.
![2021-08-21_22 14 07](https://user-images.githubusercontent.com/63221503/130329507-53537d84-9caa-4744-bedc-629d6f4d41a4.png)

**Comment by FoundationGames** [comment]
EBE does not even remotely touch nether portals, and as far as I know neither does LambdaBetterGrass
Fabric language kotlin is also not required by any of the mods in your mod list as far as I know either, you don't need it installed
**Please narrow down your mod list until you can figure out which mods SPECIFICALLY cause the issue**
Also join the discord server to post updates when testing (link on mod page)

**Comment by Precizne** [comment]
So I reduced the mod list to:

**Case 1:**
fabric-api-0.37.2+1.17.jar
iris-mc1.17-1.1.1
indium-1.0.0+mc1.17.1.jar
_lambdabettergrass-1.2.0+1.17.jar_
_enhancedblockentities-0.4.1+1.17.jar_
Shaders: Complementary Shader 4.2 dev2-dev5(Fancy Nether Portal enabled through common.glsl)

Result: 
![2021-08-22_22 21 28](https://user-images.githubusercontent.com/63221503/130363415-a6e162c0-46e2-450d-badc-ebbb89e8a975.png)

**Case 2:**
fabric-api-0.37.2+1.17.jar
iris-mc1.17-1.1.1
indium-1.0.0+mc1.17.1.jar
_enhancedblockentities-0.4.1+1.17.jar_
Shaders: Complementary Shader 4.2 dev2-dev5(Fancy Nether Portal enabled through common.glsl)

Result: 
![2021-08-22_22 26 46](https://user-images.githubusercontent.com/63221503/130363610-3c5bd811-dd70-43d9-ba14-6af622be876f.png)

**Case 3:**
fabric-api-0.37.2+1.17.jar
iris-mc1.17-1.1.1
indium-1.0.0+mc1.17.1.jar
_lambdabettergrass-1.2.0+1.17.jar_
Shaders: Complementary Shader 4.2 dev2-dev5(Fancy Nether Portal enabled through common.glsl)

Result: 
![2021-08-22_22 34 08](https://user-images.githubusercontent.com/63221503/130363733-436d57bf-a11a-4b34-b367-4b386f44536a.png)

**Case 4:**
fabric-api-0.37.2+1.17.jar
iris-mc1.17-1.1.1
indium-1.0.0+mc1.17.1.jar
Shaders: Complementary Shader 4.2 dev2-dev5(Fancy Nether Portal enabled through common.glsl)

Result: 
![2021-08-22_22 39 08](https://user-images.githubusercontent.com/63221503/130363880-d5b7aaed-b0ee-487f-8c7a-0f6e01cc27b0.png)

**Comment by Precizne** [comment]
It got fixed with new development version of Iris and Complementary Shaders. Thanks for support.
