### ISSUE TITLE
[Suggestion] Add EBE settings to Sodium video settings or to the Sodium Extra Extras tab.

### ISSUE THREAD

**Issue by K0-RR** [FoundationGames/EnhancedBlockEntities#47]
TIL EBE settings are accessible from vanilla video settings. I didn't know about it since Sodium replaces vanilla graphics settings with their own. I was using the cloth config button to get to the EBE settings which is fine but I thought Sodium users should have the main option (I think it's the main option since You added the button for it) too considering how popular Sodium is.

**Comment by FoundationGames** [comment]
You can access it from Mod Menu like most other mods' configs.
If I were to add it to Sodium Extras then it would be just as much effort to install Sodium Extras as it would be to install Mod Menu.
Will be left open for later consideration.

**Comment by Felix14-v2** [comment]
Also you can use Shift+P in Sodium settings to show vanilla video settings.

**Comment by Madis0** [comment]
I'd say it shouldn't depend on Sodium Extras, just Sodium itself as another tab.

**Comment by Scarlaid** [comment]
Sorry for necropsting, but why not [this?](https://github.com/PuzzleMC/Puzzle)
