### ISSUE TITLE
Unnecessary strings

### ISSUE THREAD

**Issue by Madis0** [FoundationGames/EnhancedBlockEntities#49]
Is there a reason why you have strings like

```
"Enhanced Chests: On",
"Enhanced Chests: Off",
```

instead of

```
"Enhanced Chests",
```
and using vanilla's strings for "On" and "Off"?
Seems like just increased complexity for the code and translators...

**Comment by triphora** [comment]
The proposed is an imperfect solution because `"%s: %s"` does not work for all languages, e.g. all RTL languages

**Comment by Madis0** [comment]
But Minecraft already has a fix for that, which is defining `%s: %s` itself as a string (`options.generic_value`).

Edit: and even `options.off.composed`, `options.on.composed` which do what you might expect.

**Comment by FoundationGames** [comment]
More freedom for translations, I don't know how every language works so I opted to keep it flexible

**Comment by Madis0** [comment]
Fair, but if there are so many duplicate strings, some of which can be inherited from vanilla anyway (more localization with less effort!), there is less initiative to translate at all.
Any language-specific issues can be handled case-by-case, e.g. vanilla's graphics' "fast/fancy" and clouds' "fast/fancy".

**Comment by FoundationGames** [comment]
This has been resolved
