### ISSUE TITLE
[Suggestion] Separate model folders for ender chests and normal chests

### ISSUE THREAD

**Issue by Simple205** [FoundationGames/EnhancedBlockEntities#51]
I've been trying to make full block chest models but using custom textures just makes both ender chests and normal chests have the same texture, Could you somehow separate the model files for ender chests and normal ones?

**Comment by FoundationGames** [comment]
The model files have always been separate
The models you see in the source for this mod are not all the models, hundreds are generated in code (and those generated models can be replaced with resource packs)
To see the generated resource pack:
- Open `.minecraft/config/rrp.properties`
- Set `dump\ assets=true`
- Open minecraft, reload resources in game
- Open `.minecraft/rrp.debug/ebe;pack/`
The full generated resource pack should be there

**Comment by Simple205** [comment]
Thank you very much for the info! I've followed the instructions but I cant find any chest models in the pack only shulker box stuff and signs. Is there something I did wrong?

**Comment by FoundationGames** [comment]
Make sure the enhanced chests/etc are actually enabled or they won't be added to the dumped resource pack

**Comment by Simple205** [comment]
Oh that's what went wrong thanks again!
