### ISSUE TITLE
[Suggestion] Compatibility with Charm

### ISSUE THREAD

**Issue by ocram9** [FoundationGames/EnhancedBlockEntities#52]
The Charm mod adds a lot of different things, one of those is chest variety (i.e. a spruce chest made out of spruce wood). These chests are still entities with this mod installed, if possible it would be nice if these chests are also optimised.

Charm: https://www.curseforge.com/minecraft/mc-mods/charm

**Comment by FoundationGames** [comment]
EBE won't come with builtin mod compatibility but a proper api for other "compatibility bridge" mods to exist may be considered
For now EBE should work fine along Charm, it just won't optimize its chests
