### ISSUE TITLE
Chests 'doubled' while open(ing) using Sodium on 1.18

### ISSUE THREAD

**Issue by Huntracony** [FoundationGames/EnhancedBlockEntities#61]
When also using Sodium (0.4.0 alpha5) on 1.18, the closed chest still renders while a chest is open/opening/closing.  Shulkers too.

![2021-12-10_13 12 46](https://user-images.githubusercontent.com/1676114/145573592-07c1629e-44aa-41df-8636-65a1c861a879.png)

**Comment by DieuDeGlace** [comment]
I can confirm that my game does the exact same. Just tested this first to see if its the culprit and it seems that it is.

**Comment by Weightierharpy3** [comment]
I Have the same exact issue only when using Sodium without Indium, are you sure you aren't forgetting to install Indium as well?

**Comment by Huntracony** [comment]
@Weightierharpy3 I did not install Indium as at the time the description on Modrinth said it wasn't needed for sodium version 0.4 and above.  But that description has since been updated so I'm assuming that was the problem and closing this issue.  Thanks!

**Comment by FoundationGames** [comment]
Back when I first wrote that description Sodium's 0.4 development builds were going to support fabric rendering api mods out of the box, it has now seemingly been delayed to a later version
