### ISSUE TITLE
Chests being rendered almost invisible

### ISSUE THREAD

**Issue by keatit71** [FoundationGames/EnhancedBlockEntities#64]
I'm not sure what causes it though i am using iris Starline branch with default enhanced shaders. The chests show textures on one side for some reason and other than that they are invisible. 
[latest.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/7739498/latest.log)

[mods.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/7739503/mods.txt)

i can also send a folder of my mods and configs if it helps.

**Comment by FoundationGames** [comment]
Iris Starline is an unofficial fork containing a lot of older, unstable prototype code, no support will be offered to people using it as it is prone to lots of random bugs
If you want shader pack settings, the Iris discord server released an official beta just a day ago adding a proper shader settings menu

**Comment by keatit71** [comment]
the version of iris that came out doesn't even have the gui yet and its the shaders themselves anyway nothing to do with the fork i'm using.

**Comment by FoundationGames** [comment]
Still, there is no reason to use Starline and as someone who wrote much of the quite unstable/experimental code in Starline, I highly recommend you use (and even help test) an official version of Iris instead
![image](https://user-images.githubusercontent.com/43485105/148596770-0959cc5f-a8c0-47fa-af11-aeab678967a5.png)

**Comment by keatit71** [comment]
i read the update notes for the new iris version the gui for shader settings isn't out yet and only accessible only if i pay them to access it so i have to wait for it to be public else i would use it over starline.

**Comment by FoundationGames** [comment]
Iris discord #public-test-builds
