### ISSUE TITLE
Enhanced chest feature removes Christmas texture

### ISSUE THREAD

**Issue by NorskNoobing** [FoundationGames/EnhancedBlockEntities#65]
If the enhanced chest option is enabled, you can't see the limited-time Christmas texture on the chests. The Christmas Chests option doesn't even do anything. I'm currently using "enhancedblockentities-0.5+1.18.jar".
![javaw_GLBu8RQ2w0](https://user-images.githubusercontent.com/39239702/147336637-fe3b79ec-50bc-4057-a0fe-fcf68a5290f7.jpg)
![javaw_1v5tAkVZJw](https://user-images.githubusercontent.com/39239702/147336639-cf863814-31f8-44a3-9bc8-2b2085fcad33.jpg)
![javaw_tMPYS2Iz7j](https://user-images.githubusercontent.com/39239702/147336640-939e7b0a-8654-47f5-af2b-dd3195854858.jpg)

**Comment by FoundationGames** [comment]
Unable to reproduce this issue, Christmas chests are still visible with EBE and Enhanced Chests enabled.
