### ISSUE TITLE
Werid texture rotation issue w/ DashLoader

### ISSUE THREAD

**Issue by azurenekowo** [FoundationGames/EnhancedBlockEntities#71]
![image](https://user-images.githubusercontent.com/67498765/149608212-e2ec98ca-af54-4e9b-92cd-e18207930fd4.png)

![image](https://user-images.githubusercontent.com/67498765/149608232-10bbe895-c2f0-47a8-a1a8-69cfc8d14a1c.png)

I have installed DashLoader, maybe that is the problem? My friends also have the same issue.

![image](https://user-images.githubusercontent.com/67498765/149608270-9eeb3e28-15db-4f98-a174-5d797ec4071e.png)

**Comment by azurenekowo** [comment]
I will update this issue when I reinstall the mod fresh w/ out DashLoader.

P/s: I use default config

![image](https://user-images.githubusercontent.com/67498765/149608333-92785e9d-db74-430d-a495-3f75c88393d5.png)

**Comment by Scarlaid** [comment]
Turn off the Experimental Chests and Enhanced Chest
Since this mod isn't supported to go well with DashLoader, you might have to wait for them to update the mod 

_The rest of the mod works fine, the chest is something that DashLoader cache breaking it_

**Comment by azurenekowo** [comment]
@Scarlaid it worked, thx

~~vinkcowisgay~~

**Comment by alphaqu** [comment]
A pull request is open in EBE that adds compat.
