### ISSUE TITLE
Sign in UI ignores custom models

### ISSUE THREAD

**Issue by muzikbike** [FoundationGames/EnhancedBlockEntities#80]
Observe how the following screenshot shows a warped wall sign with a missing texture, yet the UI still has a normal-looking texture on the sign:
![2022-02-10_19 32 56](https://user-images.githubusercontent.com/52297970/153483242-3b1a61a1-f0f1-4852-ab3e-212b1fa4928b.png)

It'd be expected that either the warped wall sign's block model would be used here instead, or that there'd be a new, dedicated, alternate block model for wall signs for when being written on in the UI (this option may be preferable to avoid any potential issues caused by rendering the whole 3D model in the UI).

**Comment by FoundationGames** [comment]
Fixed in latest commit
