### ISSUE TITLE
Block entities settings menu does not have a darkened background

### ISSUE THREAD

**Issue by muzikbike** [FoundationGames/EnhancedBlockEntities#81]
Inconsistent with all the other transparent menus - shouldn't it have one?
![2022-02-10_19 38 31](https://user-images.githubusercontent.com/52297970/153487127-52bafb1c-1b2c-4493-9d33-3fa2245bd5a8.png)

**Comment by FoundationGames** [comment]
This is to allow you to see small visual changes between settings clearly (working as intended)
