### ISSUE TITLE
Bed items still seem to use the entity model

### ISSUE THREAD

**Issue by muzikbike** [FoundationGames/EnhancedBlockEntities#83]
Found this while fixing the two hidden faces issues. In spectator, entering a dropped bed item showed that one white plane that bed halves contain in vanilla for some reason, alongside top faces for the legs which shouldn't exist as I removed them from the model. Shouldn't bed models also be converted over to proper models since the blocks are?
![2022-02-10_21 52 43](https://user-images.githubusercontent.com/52297970/153514838-14d35352-cbc2-4445-97d4-4b38d862ad11.png)

**Comment by FoundationGames** [comment]
Fixed in latest commit
