### ISSUE TITLE
1.18.2 Update

### ISSUE THREAD

**Issue by MaxBr5** [FoundationGames/EnhancedBlockEntities#86]
1.18.2 pre-1 changed modding quite a bit so please make some changes for 1.18.2 compatibility.

**Comment by triphora** [comment]
can't do anything without ARRP not being updated

**Comment by MaxBr5** [comment]
Why don't you remove the dependency and do some java programming around the missing dependency or fork the bad dependency to update it.

**Comment by Lolothepro** [comment]
ARRP has been updated for Minecraft 1.18.2

**Comment by FoundationGames** [comment]
The mod is not updated for 1.18.2

**Comment by uselessSABOTAGE** [comment]
Can confirm this mod causes a crash when loading 1.18.2.  Please fix, thanks!

**Comment by giorov** [comment]
[crash-2022-03-05_13.48.01-client.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/8191545/crash-2022-03-05_13.48.01-client.txt)

**Comment by NightEule5** [comment]
I tried working around this by updating ARRP in the Jar, but there's another problem:

[crash-2022-03-07_19.17.25-client.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/8202200/crash-2022-03-07_19.17.25-client.txt)

I appears this mod is having the exact same issue as [LambdaBetterGrass#45](https://github.com/LambdAurora/LambdaBetterGrass/issues/45)

**Comment by giorov** [comment]
[NightEule5](https://github.com/NightEule5) commented [4 days ago](https://github.com/LambdAurora/LambdaBetterGrass/issues/45#issuecomment-1061321650) "The mixin for net.minecraft.class_3304 which maps to net.minecraft.resource.ReloadableResourceManagerImpl is failing. The method method_14475, which maps to addPack in 1.18.1, is missing from 1.18.2's mappings. It must've been removed"

No idea if that is helpful or if it's a confabricate dependency or what.

**Comment by ghost** [comment]
FYI the author is not inactive but there is no ETA

![image](https://user-images.githubusercontent.com/82549089/157916288-f98412df-38a4-4211-875d-f411f4f1f9ed.png)
