### ISSUE TITLE
1.18.2 instant crash

### ISSUE THREAD

**Issue by ghost** [FoundationGames/EnhancedBlockEntities#87]
When trying to use on minecraft 1.18.2 the game instant crashes

crash log: [crash-2022-03-04_12.22.40-client.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/8188301/crash-2022-03-04_12.22.40-client.txt)

latest log: [latest.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/8188303/latest.log)

mods:
ebe 0.5-1.18
fabric api 0.47.8-1.18.2
fabric loader 0.13.3
lazy dfu 0.1.2

**Comment by Lolothepro** [comment]
Known bug #86

**Comment by FoundationGames** [comment]
Duplicate
