### ISSUE TITLE
1.18.2 Can't get example EBE Resource Pack

### ISSUE THREAD

**Issue by GrandPappyJay** [FoundationGames/EnhancedBlockEntities#90]
The steps listed to dump the Example EBE Resource Pack Files doesn't work at all on 1.18.2... I downgraded to 1.18.1 and it worked fine...  A dev on another project mentioned that there were changes to how resources are reloaded in 1.18.2, maybe that will help you.

I tested with only the following loaded...
EBE v0.6 1.18.2
fabric-api-0.48.0+1.18.2
modmenu-3.1.0

**Comment by PweSol** [comment]
Could be why there are some issues with resource packs that change what EBE changes as well.

**Comment by muzikbike** [comment]
I do hope that gets fixed, as custom sign models were a huge bonus.

**Comment by FoundationGames** [comment]
Dedicated solution added as of latest commit

**Comment by muzikbike** [comment]
Signs ignoring models definitely is also fixed (#79 is, however, still an issue):
![2022-06-24_09 23 25](https://user-images.githubusercontent.com/52297970/175496313-6617e3c0-b959-415b-b04d-85cb81e09bc7.png)
