### ISSUE TITLE
[1.18.2] EBE Does not apply models from resource pack

### ISSUE THREAD

**Issue by Jarfeh** [FoundationGames/EnhancedBlockEntities#91]
When using this resource pack (I made it so I can use this and the golden days pack), EBE does not apply the models that I made. This pack worked fine in 1.18.1.

Resource Pack:
[golden-days-ebe.zip](https://github.com/FoundationGames/EnhancedBlockEntities/files/8359934/golden-days-ebe.zip)

**Comment by FoundationGames** [comment]
I know why this is happening I completely overlooked something when changing the resource stuff to work in 1.18.2
Should be fixed next release

**Comment by Baxmann** [comment]
Any progress on this?

**Comment by FoundationGames** [comment]
Fixed in latest commit
