### ISSUE TITLE
1.18.2 - EBE v0.6 for 1.18.2 - Optifabric & Optifine

### ISSUE THREAD

**Issue by CERIBES** [FoundationGames/EnhancedBlockEntities#93]
Game crashes with exit code 255 when logging into server or single player game.

**Comment by Raconteur32** [comment]
I think I have the same. When used with optifabric and optifine, this mod just make my game crash when joining a solo world or juste after I join.

Log error:
https://bytebin.lucko.me/hv1qtHKoKD

**Comment by FoundationGames** [comment]
Optifabric and OptiFine will no longer be supported with the next EBE update. They make breaking changes to the code that I cannot circumvent.
