### ISSUE TITLE
Thank you for Great Mods! Modded Block Entity Support Please?

### ISSUE THREAD

**Issue by ardissaps** [FoundationGames/EnhancedBlockEntities#97]
Thank you for your great mods!
Please support these mods chest, they are so laggy :
https://modrinth.com/mod/Charm
https://www.curseforge.com/minecraft/mc-mods/betternether
https://www.curseforge.com/minecraft/mc-mods/betterend

**Comment by FoundationGames** [comment]
EBE will not add support for other mods by default. Though, EBE's codebase is designed to be extensible so anybody could make a compatibility bridge if they so desired.
